### ISSUE TITLE
Guard against broken transcryption migrations (or "transcryptions")

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/transcryptor#15]
From @dadooda

> Data transcryption must always take place in a controlled transaction, since things half-done might ruin existing data. Combining it with Rails migration specifics might make things unnecessarily difficult. It’s comparatively easy to spook Rails with a carelessly written migration and then not to be able to roll the spoiled data back.

**Comment by ronaldtse** [comment]
Maybe this comes in a form of a two-stage migration similar to zero-downtime migration ( #5 ).

**Comment by ribose-jeffreylau** [comment]
In the event of a failure, there's currently no way to tell the statuses of each table row.
There needs to be a way to know which rows have been successfully migrated, those that are yet to be migrated, and maybe also the row that caused the failure (could perhaps be inferred from the above two sets?).

Perhaps we can start by having a _memo column_ automatically created for each transcryption, and removed at the end of a successful transcryption.  Something along the line of:

```ruby
# class Transcryptor::Instance
  def re_encrypt(table_name, attribute_name, old_opts, new_opts, other_columns = [])
    # ...
    memo_column_name = :"transcryption_memo_#{attribute_name}"
    adapter.add_column table_name, memo_column_name, :boolean, default: false

    rows.each do |old_row|
      decrypted_value = # ...
      new_row = # ...
      adapter.update_row_with_memo(memo_column_name, table_name, old_row, new_row)
    end

    adapter.remove_column table_name, memo_column_name

  end
```

where `#update_row_with_memo` could be something like:
```ruby
# class Transcryptor::AbstractAdapter
  def update_row_with_memo(memo_column_name, table_name, old_values, new_values)
    update_row(
      table_name,
      old_values,
      new_values.merge(memo_column_name => true)
    )
  end
```

With this, then it should be easy to see where the failure occurred.
After dealing with the offending row, _etc._, the admin can then choose to run `db:migrate` again.
Transcryptor now sees that the memo field has already been created, so it picks up from where it left off:

```ruby
# class Transcryptor::Instance (Version 2, modified from the above snippet)
  def re_encrypt(table_name, attribute_name, old_opts, new_opts, other_columns = [])
    # ...
    memo_column_name = :"transcryption_memo_#{attribute_name}"
    rows = if adapter.column_exist?(table_name, memo_column_name)
      adapter.select_rows_where(table_name, all_columns, memo_column_name => false)
    else
      adapter.add_column table_name, memo_column_name, :boolean
      adapter.select_rows(table_name, all_columns)
    end

    rows.each do |old_row|
      decrypted_value = # ...
      new_row = # ...
      adapter.update_row_with_memo(memo_column_name, table_name, old_row, new_row)
    end

    adapter.remove_column table_name, memo_column_name

  end
```

So now, what needs to be implemented are:
- `adapter.column_exist?(table_name, column_name)` : `Bool` true if column `column_name` exists in table `table_name`;
- `adapter.select_rows_where(table_name, columns, where_map)` : `Enumerable` of the `SELECT`-ed rows, conditional on the equalities specified in `where_map`;
- `adapter.update_row_with_memo(memo, table, old_vals, new_vals)` as above.

Any advice would be appreciated :-)

**Comment by ronaldtse** [comment]
Thanks @ribose-jeffreylau, I remembered we talked about this before being a MUST and already forgot about it! I'm sure @DmitryDrobotov would have good ideas :-)

**Comment by ribose-jeffreylau** [comment]
Just realized that dropping columns in SQLite would be a bit painful as it's not as straight-forward as other SQL implementations.

See: https://stackoverflow.com/questions/5938048/delete-column-from-sqlite-table/5987838#5987838

**Comment by ribose-jeffreylau** [comment]
Also, it seems that Active Record handles SQLite `DROP COLUMN` better than DataMapper.
In my short tests, AR doesn't bail and actually removes the column whereas in DM, it gives me a SyntaxError:
```
DataObjects::SyntaxError:
       near "DROP": syntax error
```

**Comment by DmitryDrobotov** [comment]
To be honest, I am not really support this idea.

Some points:
1. Standard Rails migration is performing in a single transaction (by default), so here is no need to use any additional columns or something. If sth failed all information can be found in `development.log` (not sure about `production.log`, likely it requires different log level configuration).
2. It is absolutely useless for zero-downtime migrations. To detect such error we can just simply raise exception and rollback `UPDATE` transaction.
3. If gem user has a big amount of data I'd recommend to use `zero-downtime` feature of the gem. Also he can create a rake task which can migrate each row separately (needs to be implemented). So, it will allow to provide an ability for him to choose the way how to handle errors.
3. Gem should be clean, easy-to-use, and understandable. It really looks like overhead when it will start to create or drop columns or even made some other hidden manipulations with the database. :)

**Comment by ribose-jeffreylau** [comment]
Agreed.  Very good points.  Point 3 seems it would be flexible enough.
To make it easier to know the progress of the migration in the event of a failure, I think Transcryptor could migrate rows in a predefined sorted order.  The sys admin can then follow the logs along with the same sorted order to know which rows haven't been migrated yet.

But anyway, I think using `zero-downtime` with sufficient logging outputs would have this issue covered.

A "`--dry-run`" mode could even test out decryption and validate re-encrypted values without touching the DB, as a precautionary measure.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau this issue can be superseded with issue #5, right? If so we can close it and move the additional requirements there?

**Comment by ribose-jeffreylau** [comment]
Pretty much.
