### ISSUE TITLE
Interface for a user to generate a migration

### ISSUE THREAD

**Issue by GildedHonour** [riboseinc/transcryptor#16]
Create an interface for a user to generate a migration(s), something like:

    rails generate transcryptor migration name [here can be a list of fields]

Tables' names and fields might be provided as an argument.

**Comment by GildedHonour** [comment]
1)

    rails generate transcryptor migration [the name of a table] [optional fields] [maybe some other arguments]

If a list of fields is specified, it'll re-encrypt only those fields, otherwise it'll look for all the fields "encrypted_{field_name}" and re-encrypt those for a given table.

For each field it'll create "encrypted_{field_name}_updated_at" field where it'll store the current date.

The old and new algorigthms, keys, IVs will be provided via config.

I think that attr_encrypted has too many settings therefore it can be confusing. It's more flexible, it could be more secure, but that bring a complexity as well. For instance, why would a user want to encrypt one field with one key and another field with another key, in the same table? Or even in different tables. Thus, in transcryptor we should reduce the amount of settings for a user. 

2) Before the first use, there're no "encrypted_{field_name}_updated_at" fields. How then the gem will know when a field was encrypted so that it can remind a user when a time comes to re-encrypt it? I think we should then create the 2nd generator which will be run first:

    rails generate transcryptor init

It'll inspect all the tables and their fields and create "encrypted_{field_name}_updated_at" for each encrypted field and set it to the current date.

**Comment by DmitryDrobotov** [comment]
I do not think that we need interface for generation. Because it is pretty simple already. https://github.com/riboseinc/transcryptor#activerecordmigration
Closing issue.
