### ISSUE TITLE
Documentation insufficient

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/transcryptor#2]
There are many undocumented configurations, and would benefit from having documenation.
These include:
- `encode64_*` and `decode64_*` for both `transcryptor.enc` and `.dec`,
- allowed parameter types for `iv` and `salt` for `transcryptor.enc`,
  - `true|false`, `String`, ...?
- _etc._

**Comment by DmitryDrobotov** [comment]
Added in https://github.com/riboseinc/transcryptor/commit/9c1673098fe9f30646b76bcd98c83057971d30af
