### ISSUE TITLE
attr_encrypted_poro_class doesn't contain all fields from the originating Model

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/transcryptor#22]
# Context
Inside a migration file, we specify the configs like so:
```ruby
class RemoveSaltFromStuff < ActiveRecord::Migration

  def old_configs
    { # old configuration of attr_encrypted for column
      key:           ->(u) { ENV['key'] },
      mode:          :per_attribute_iv_and_salt,
      algorithm:     'aes-256-cbc',
      encode_salt:   false,
      insecure_mode: true,
    }
  end

  def new_configs
    { # new configuration of attr_encrypted for column
      key:       ->(u) { ENV['key'] },
      mode:      :per_attribute_iv,
      algorithm: 'aes-256-gcm',
    }
  end

  def up
    re_encrypt_column :keys, :stuff,
                      old_configs,
                      new_configs
  end

  def down
    re_encrypt_column :keys, :stuff,
                      new_configs,
                      old_configs
  end

end
```
# What is expected
The `u` in the `->(u) { ENV['key'] }` would be an object that has access to all the column values of the row that Transcryptor is iterating on.

# What actually happens
`u` is instead instantiated with a PORO object but only contains the encrypted field and its metadata (`@encrypted_stuff` and `@encrypted_attributes` in this example).

**Comment by ribose-jeffreylau** [comment]
Not sure if bug or enhancement 🤔 

Anyway, the expectation here is _not_ for `u` to be an ActiveModel, _etc._  Just being a column-filled PORO should be sufficient.

**Comment by ribose-jeffreylau** [comment]
Ideally a Migration would work like so:
```ruby
class RemoveSaltFromStuff < ActiveRecord::Migration

  def derive_key(*args)
    # ... e.g., some complicated key derivation
  end

  def old_configs
    { # old configuration of attr_encrypted for column
      key:           ->(u) { derive_key(u.password_hash, u.birthday, ENV['key']) },
      mode:          :per_attribute_iv_and_salt,
      algorithm:     'aes-256-cbc',
      encode_salt:   false,
      insecure_mode: true,
    }
  end

  def new_configs
    { # new configuration of attr_encrypted for column
      key:       ->(u) { derive_key(u.favorite_color, ENV['key']) },
      mode:      :per_attribute_iv,
      algorithm: 'aes-256-gcm',
    }
  end

  def up
    re_encrypt_column :keys, :stuff,
                      old_configs,
                      new_configs
  end

  def down
    re_encrypt_column :keys, :stuff,
                      new_configs,
                      old_configs
  end

end
```

However, Transcryptor currently doesn't know about the column names of the table.
There seems to be two ways around this:
1. Make Transcryptor query the schema itself, like `PRAGMA table_info(table_name);` for sqlite3, or
2. Let the user specify the needed column names so Transcryptor doesn't have to take care of mapping column names to all column values, _e.g.,_
```ruby
  def up
    re_encrypt_column :keys, :stuff,
                      old_configs,
                      new_configs,
                      %i[birthday password_hash favorite_color]
  end
```
This means breaking the current signature of `Transcryptor::Instance#re_encrypt_column(table_name, attribute_name, ...)`, but that may not matter much for now.

What are your thoughts?
cc: @DmitryDrobotov

**Comment by DmitryDrobotov** [comment]
Sounds good and seems to be implemented already (https://github.com/riboseinc/transcryptor/pull/23) 👍
